-- Tabla de usaurios
CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_COMPLETO TEXT NOT NULL,
    USUARIO TEXT NOT NULL UNIQUE,
    ACTIVO INTEGER NOT NULL CHECK (ACTIVO IN (0,1)),
    ACTIVO_LDAP INTEGER NOT NULL CHECK (ACTIVO_LDAP IN (0,1)),
    CORREO TEXT UNIQUE,
    USUARIO_CREO TEXT,
    IP_CREO TEXT,
    USUARIO_MODIFICO TEXT,
    IP_MODIFICO TEXT,
    ID_ENTIDAD INTEGER NOT NULL,
    ROL_ID INTEGER,
    FOREIGN KEY (ROL_ID) REFERENCES ROL (ID_ROL) ON DELETE SET NULL
);

-- Tabla de roles
CREATE TABLE ROL (
    ID_ROL INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL UNIQUE,
    DESCRIPCION TEXT,
    ACTIVO INTEGER NOT NULL CHECK (ACTIVO IN (0,1)),
    USUARIO_CREO TEXT,
    IP_CREO TEXT,
    USUARIO_MODIFICO TEXT,
    IP_MODIFICO TEXT
);

-- Tabla de permisos
CREATE TABLE PERMISO (
    ID_PERMISO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL UNIQUE,
    USUARIO_CREO TEXT,
    IP_CREO TEXT,
    USUARIO_MODIFICO TEXT,
    IP_MODIFICO TEXT
);

-- Tabla intermedia ROL_PERMISOS (relación muchos a muchos)
CREATE TABLE ROL_PERMISOS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ROL_ID INTEGER NOT NULL,
    PERMISO_ID INTEGER NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES ROL (ID_ROL) ON DELETE CASCADE,
    FOREIGN KEY (PERMISO_ID) REFERENCES PERMISO (ID_PERMISO) ON DELETE CASCADE,
    UNIQUE (ROL_ID, PERMISO_ID) 
);